### ISSUE TITLE
Update getting started page

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#30] opened 2015-06-02 11:09 UTC
http://www.tdwg.org/getting-started/
Donald Hobern's name (A TDWG overview) links to executive page;  Text in bottom table (Michael Giddens, Cynthia Parr) not visible due to colour

**Comment by pmergen** [comment] 2015-06-10 10:28
Quite some information here is indeed out dated. The issue is also linked to new TDWG website ?

**Comment by sblum** [comment] 2015-06-28 23:30
I fixed the text color problem in the table, also background color for one row, and partial text surrounded by an anchor tag (<a>), on the new site.

I have not updated any of the content.  I think that's a broader issue, and should be coordinated with updating the basic recommendations on the homepage.  I think those need to be done by a group representing a TDWG consensus, not a single person's opinion.  Closing this smaller issue.

**Closed as completed by sblum** 2015-06-28 23:30 UTC
